Switching to UF2 image format
amperka/Espruino pull request #7
Opened 2022-05-26 10:59 UTC by kekcheburec

Переход на UF2 формат

2022-05-26 11:12 UTC, nkrkv requested changes

2022-05-26 11:12 UTC, nkrkv commented on scripts/create_iskrajsmini_image.sh
> +./scripts/uf2conv.py -c -b 0x08008000 -f STM32F4 $ESPRUINOFILE -o $IMGFILE  || { echo 'Build failed (uf2)' ; exit 1; }
В скриптах используем полные наименования свитчей комманд-лайна. `-c`, `-b`, `-f` и т.п. хороши при постоянной интерактивной работе, чтобы меньше кнопок нажимать; а в скриптах гораздо более понятны для дальнейшей поддержки полные имена.

2022-05-26 11:12 UTC, nkrkv commented on scripts/uf2conv.py
> +#!/usr/bin/env python3
Какова история происхождения этого файла? Стоит добавить комментарий, описывающий откуда этот тул позаимствован, и что он делает: очень общё, на вход то-то, на выход сё-то.

2022-05-26 14:41 UTC, kekcheburec commented
@nkrkv, все исправлено?

2022-05-27 10:49 UTC, nkrkv approved these changes
LGTM

2022-05-27 10:49 UTC, merged